### ISSUE TITLE
Badly formatted translations crash the server process

### ISSUE THREAD

**Issue by ntrrgc** [guigrpa/mady#1]
How to reproduce:

1. Click any translation field in the UI.
2. Write `{`, or just any MessageFormat with oddly matched braces.
3. Press Tab.

An exception is thrown. Since the exception is thrown inside an asynchronous callback without a try/catch ([_.debounce](https://lodash.com/docs#debounce) :bomb:), it reaches the node.js main loop. Boom. The entire server process crashes. And no traceback whatsoever of who called the errored function. 
```
/tmp/guigrpa-mady-9485b5e/src/server/db.js:395
        throw _iteratorError2;
        ^

Error: Parser error with `exampleContext_{NUM, plural, one{1 hamburger} other{# hamburgers} }`: SyntaxError: Expected "=", "}" or identifier but end of input found.
    at compileMsg (/tmp/guigrpa-mady-9485b5e/node_modules/messageformat/lib/messageformat.js:483:17)
    at MessageFormat.compile (/tmp/guigrpa-mady-9485b5e/node_modules/messageformat/lib/messageformat.js:508:21)
    at compileTranslations (compileTranslations.js:33:24)
    at _compileTranslations (db.js:286:25)
    at invokeFunc (/tmp/guigrpa-mady-9485b5e/node_modules/lodash/lodash.js:9402:23)
    at trailingEdge (/tmp/guigrpa-mady-9485b5e/node_modules/lodash/lodash.js:9450:18)
    at Timeout.timerExpired (/tmp/guigrpa-mady-9485b5e/node_modules/lodash/lodash.js:9437:18)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

npm ERR! Linux 4.5.1-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! mady@1.0.3 start: `babel-node src/server/startup`
npm ERR! Exit status 1
```
It's kind of funny that less than 12 hours after [I extensively wrote about this problem with node.js server programming in general](https://github.com/Microsoft/TypeScript/issues/8392) I find it crashing applications on the wild.

You may want to do **all** your asynchronous staff with promises in order to be able to catch errors, since those have a built-in try catch that avoid them reaching the main loop and a mechanism to gracefully react to them (promise rejection). You may also want to have long stack traces in order to track what is causing the errors.

**Comment by guigrpa** [comment]
Thanks for the report! It has been corrected with my latest commit.

@ntrrgc Regarding promises and long stack traces, I also use them in mady (see [server/startup.js](https://github.com/guigrpa/mady/blob/master/src/server/startup.js)), but clearly not in this case with the debounced `compileTranslations()` (it was synchronous originally).
