### ISSUE TITLE
Possible bug: how are multiple translations for same key handled?

### ISSUE THREAD

**Issue by sullivanpt** [guigrpa/mady#13]
I'm confused by this feature. I toggled the FUZZY (yield sign) icon in the UI and I ended up with this in my es.json file.  Notice, the same 'keyId' appears twice.  Code inspection seems to indicate "last one wins", but since this is a JSON object, not an array, I think the sort order is dubious.  And actually, when I look in my 'es.out.json' the FUZZY takes priority over the hand edited one.

```
 "7560a2b6-2d85-4021-a0e3-0fd04e927dd6": {
    "id": "7560a2b6-2d85-4021-a0e3-0fd04e927dd6",
    "isDeleted": false,
    "lang": "es",
    "translation": "los lagartos están calientes",
    "fuzzy": false,
    "keyId": "bGl6YXJkcyBhcmUgaG90"
  },
  "943d7b7b-9ad4-4567-8a55-032525504f47": {
    "id": "943d7b7b-9ad4-4567-8a55-032525504f47",
    "isDeleted": false,
    "lang": "es",
    "translation": "los lagartos están calientes",
    "fuzzy": true,
    "keyId": "bGl6YXJkcyBhcmUgaG90"
  }
```

I'm not sure what's supposed to happen here. Once I understand the intent I'd like to try to make a fix. Thanks.

(Actually, looking closer I don't think this is supposed to happen. I'm guessing it is a race condition).

**Comment by guigrpa** [comment]
I couldn't reproduce the issue. Activating the fuzzy icon resulted in just the affected translation being modified:

```diff
     "lang": "es",
     "translation": "No se pudo guardar la configuración",
-    "keyId": "ZXJyb3JfQ29uZmlndXJhdGlvbiBjb3VsZCBub3QgYmUgc2F2ZWQ="
+    "keyId": "ZXJyb3JfQ29uZmlndXJhdGlvbiBjb3VsZCBub3QgYmUgc2F2ZWQ=",
+    "fuzzy": true
   },
```

It would be useful if you could prepare a small repo reproducing the case.

**Comment by guigrpa** [comment]
*Los lagartos están calientes* OMG! 👍

**Comment by sullivanpt** [comment]
Hmmm, I'm getting duplicate keyId pretty consistently; maybe it's another Win10 issue.  I'll dust of my Mac in the next few days, and let you know if the behavior is different for me.

**Comment by guigrpa** [comment]
Great! I’ll reopen the issue for the time being, to keep track

**Comment by guigrpa** [comment]
Great!

**Comment by sullivanpt** [comment]
I'm not recreating this on anymore. Might have had to do with the fact that my watcher was including mady's output folder at the time.
