### ISSUE TITLE
Error extracting React Intl messages

### ISSUE THREAD

**Issue by jagratiTomar** [guigrpa/mady#16]
@guigrpa  So I am new to mady and exploring possibilities it provides. In my react project I am using react-intl. I tried extracing existing messages from my project and ran `npm run translate` . when refresing the messages tab in mady UI. I got this error in console. Please explain to me why this error is coming and how to fix it.

```
 watch INFO  CHANGE on app/translations/keys.json
2018-09-06T07:04:42.409Z               parser INFO  Processing app/translations/keys.json...
2018-09-06T07:04:42.732Z               parser ERROR Error extracting React Intl messages
                                       parser ERROR   name: 'SyntaxError'
                                       parser ERROR   message: 'unknown: Unexpected token, expected ; (2:28)'
                                       parser ERROR   stack: SyntaxError: unknown: Unexpected token, expected ; (2:28)
                                       parser ERROR   stack:   1 | {
                                       parser ERROR   stack: > 2 |   "RGltZW5zaW9uIE5hbWUuLi4=": {
                                       parser ERROR   stack:     |                             ^
                                       parser ERROR   stack:   3 |     "id": "RGltZW5zaW9uIE5hbWUuLi4=",
```

**Comment by guigrpa** [comment]
Would it be possible to move `app/translations` outside `app`? This would prevent Mady from processing the `app/translations` folder, which I believe is causing the issue.

**Comment by jagratiTomar** [comment]
sure I'll try that.

**Comment by guigrpa** [comment]
Did it work?

**Comment by jagratiTomar** [comment]
yes it worked. Thanks. However is there a way to exclude that particular folder??

**Comment by guigrpa** [comment]
As another workaround, you could explicitly list all subfolders inside `app`, except `translations`.
