### ISSUE TITLE
Mady translations showing up blank

### ISSUE THREAD

**Issue by gfcf14** [guigrpa/mady#18]
Hi @guigrpa , I've been trying to use mady in order to translate text for my project, formatted this way:
```
export const ENGLISH_STATE = {
  lang: 'en',
  messages: {
    'label': 'English',
    'login.password': 'Password',
    'login.confirm': 'Confirm Password',
  },
};
```

Because my project needs to follow this format, I thought of using the Regex option in order to add the text I want and see its translation:

<img width="397" alt="screen shot 2018-10-09 at 12 46 41 pm" src="https://user-images.githubusercontent.com/716412/46689804-a95dd300-cbce-11e8-89a1-e0c4cd66ae48.png">

And, while that works, the translated text appears blank:

<img width="1137" alt="screen shot 2018-10-09 at 12 51 07 pm" src="https://user-images.githubusercontent.com/716412/46689830-bda1d000-cbce-11e8-8b95-aca948919b44.png">

I've also tried formatting my text so it looks like a function:

<img width="307" alt="screen shot 2018-10-09 at 2 23 18 pm" src="https://user-images.githubusercontent.com/716412/46689900-f04bc880-cbce-11e8-8d2e-cff504543f84.png">

But the same issue persists:

<img width="1136" alt="screen shot 2018-10-09 at 2 24 18 pm" src="https://user-images.githubusercontent.com/716412/46689940-0b1e3d00-cbcf-11e8-8c96-48d22248750f.png">

Why would this be happening? Please help me understand if I'm not using it right. Should you need it, here is my config.json file:

```
{
  "dbVersion": 2,
  "srcPaths": [
    "src/testtranslation"
  ],
  "srcExtensions": [
    ".js",
    ".jsx",
    ".coffee",
    ".cjsx"
  ],
  "langs": [
    "en",
    "es",
    "ca",
    "en-US",
    "en-GB"
  ],
  "msgFunctionNames": [
    "_t"
  ],
  "msgRegexps": [
    "(?<=: ')(.*)(?=')"
  ],
  "fJsOutput": true,
  "fMinify": false,
  "fJsonOutput": true,
  "fReactIntlOutput": true,
  "originalLang": "en"
}
```

**Comment by gfcf14** [comment]
The problem I have is that the translations don't show. Like, wouldn't the `es` section say `label2 Ingles` for example?

**Comment by gfcf14** [comment]
I'm sorry. I'm afraid I misunderstood. I believed the program was supposed to translate it all for you

**Comment by guigrpa** [comment]
No worries, I'm glad you figured it out!

Note however that Mady can help you with automatic translation based on Google Translate.

**Comment by Sashkan** [comment]
@guigrpa how can I translate missing translations using the Google Translate integration ? I saw the button on each translations, but is there a way to apply this to all missing ones ?
