### ISSUE TITLE
Working with React-Intl

### ISSUE THREAD

**Issue by kumarharsh** [guigrpa/mady#3]
Reading the readme, it semes that mady *only* works when message strings are wrapped in mady's own `_t` function. So, on first look it doesn't seem possible to extract react-intl's `<FormattedMessage ...` jsx syntax, or `intl.formatMessage()`. Is support for react-intl in the roadmap?

An alternative can be that I extract all my strings from my app into one JSON file, say `en.json` in this format:

```
[
  {
    "id": "PasswordForm.passwordField.label",
    "defaultMessage": "Choose your Password",
    "description": "Field lable for the password field"
  },
  ...
]
```
but then mady should be able to read this file and treat this as the keys database.

**Comment by guigrpa** [comment]
There are three parts to Mady: string extraction (1), translation and compilation (via Mady's web application) (2), and integration of the translated messages in your application (3). The `_t` function is used for both marking messages for extraction, as well as to use them later on (1 and 3). 

If *string extraction* is what prevents you from integrating with react-intl, I can easily make it configurable how Mady finds those strings (just including the regex pattern in Mady configuration). Would that be enough? How about (3) then? I'm not sure how you could do that to integrate the compiled locales with React-Intl's components and API... Maybe you can enlighten me about that.

**Comment by guigrpa** [comment]
@kumarharsh Customisation of translation function names has been added in d011d57.

**Comment by guigrpa** [comment]
@kumarharsh Check back soon, I'm working on React Intl integration!

**Comment by bjrn** [comment]
hi @guigrpa, is react-intl supported in the current npm version? I'm looking into using react-intl for a react native app, and mady looks very much like the translation tool I'd like to provide to that project.

**Comment by guigrpa** [comment]
@bjrn It does, yes, starting with v2.0.0. Looking forward to your feedback!

**Comment by bjrn** [comment]
ah, installed it in my project now, but it doesn't seem to pick up my messages... i'm using the HOC `injectIntl`, defining my messages with `defineMessages` and then using `formatMessage( )` inside my components.

I'm not using the `<FormattedMessage />` component from react-intl anywhere yet since I'm passing strings as props.

I've added `formatMessage` to message translation function in the config...

Am I missing something obvious in my setup?

**Comment by bjrn** [comment]
btw, it picks up tags when using the `_t()` function from Mady, but that seems to break on react native. But that's another issue.

**Comment by guigrpa** [comment]
Mady uses `babel-plugin-react-intl` as peer dependency to parse your React Intl sources. Have you installed this dependency? Maybe you can check your logs to see whether there are any React Intl - related messages you can share?

**Comment by bjrn** [comment]
Yes, and I have it running in the project, and it works via [react-intl-translations-manager](https://www.npmjs.com/package/react-intl-translations-manager), but somehow, when running mady, it doesn't pick up any messages at all...

**Comment by guigrpa** [comment]
@bjrn I'm not using React Intl for any of my projects (just added support here due to a feature request), so I'm not sure about your use case. I'd be glad to help if you can provide a small repo or config instructions to reproduce the issue...

**Comment by guigrpa** [comment]
@bjrn Btw, please open the separate issue on Mady not picking tags with `_t()` in React Native. I used it not long ago in a RN project and it was just fine, so please report on any regression you may find.
