### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cesarvarela** [guigrpa/mady#6]
HI! I want to use mady alongside nunjucks for static html translation/generation. For that I need 2 things:

- ability to save keys to a static JSON file
- search for keys in nunjucks template format `{{ keyname }}`

How difficult do you think this could be?

**Comment by guigrpa** [comment]
Shouldn't be hard at all. Even less, now that we have React Intl interoperability, which is similar in some aspects.

I will address it in the next release!

**Comment by guigrpa** [comment]
Hmmm, I think I misunderstood your original explanation. Let me check if I understand it correctly now:

* You don't want to use Mady's *parsing* functionality (which extracts the *keys* from your source files)
* You'd rather **create keys** via the UI (something that's not currently possible)
* You don't want to use Mady's *runtime* functionality either (i.e. the *translate* function), but rather let Mady store keys and translations in a JSON file (per language) and build your own integration

Is that right?

**Comment by cesarvarela** [comment]
Hi!
- I do, but since I'm using `nunjucks` to generate a static site, I'm not sure if its possible to parse their template syntax correctly, specifically: `{{ expression }}`
- Manually adding keys using the ui allows you to work with any template engine, without worring about its syntax 
- Yep, this is a static site, and I already have have the integration done to load `.json` files with the keys and their contents. But I have to maintain those `.json` files manually and it is a PITA. 

So, in my setup I have:

```
es.json
en.json
fr.json
```

And in each of them, something like:

en.json:
```
{
  key_name: "This is the text"
}
```
es.json:
```
{
  key_name: "Este es el texto"
}
```
and so on.

**Comment by guigrpa** [comment]
I finally added **parsing with custom regexps** (22c5020) and **generic JSON generation** (2893d01). In principle, this should meet your needs: have a look at the example regexp I include as a placeholder in the UI, which would be the one you need: `{{\s*(.*?)\s*}}`.
